// SPDX-License-Identifier: Apache-2.0

//! `ozerk` — OZERK geliştirici CLI iskeleti / OZERK developer CLI skeleton.
//!
//! TR: Bu araç şimdilik bir iskelettir; alt komutlar Manifesto §12'deki
//! geliştirici akışını izler ancak henüz gerçek işlev taşımaz.
//! EN: This tool is a skeleton for now; the subcommands follow the developer
//! flow in Manifesto §12 but carry no real functionality yet.

use std::io::{ErrorKind, Write};
use std::path::Path;
use std::{fs, process};

use clap::{Parser, Subcommand};

/// TR: `ozerk init` ile üretilen taslak uygulama manifesti.
/// EN: Draft application manifest generated by `ozerk init`.
const OZERK_TOML_TEMPLATE: &str = include_str!("../templates/ozerk.toml");

#[derive(Parser)]
#[command(
    name = "ozerk",
    version,
    about = "OZERK geliştirici aracı (iskelet) / OZERK developer tool (skeleton)",
    long_about = "TR: OZERK uygulamaları için geliştirici aracı. Şimdilik bir iskelettir; \
                  yalnızca `init` taslak bir ozerk.toml üretir, diğer komutlar ne yapacaklarını \
                  açıklayıp çıkar.\n\
                  EN: Developer tool for OZERK applications. Currently a skeleton; only `init` \
                  generates a draft ozerk.toml, the other commands explain what they will do and exit."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Taslak ozerk.toml uygulama manifesti üretir. / Generates a draft ozerk.toml application manifest.
    Init,
    /// Uygulamayı yerelde/emülatörde çalıştıracak. / Will run the app locally or in the emulator. (iskelet / skeleton)
    Run,
    /// Uygulama testlerini çalıştıracak. / Will run the application tests. (iskelet / skeleton)
    Test,
    /// Manifestteki izin beyanlarını denetleyecek. / Will audit the permission declarations in the manifest. (iskelet / skeleton)
    Permissions,
    /// Uygulama paketini derleyecek. / Will build the application package. (iskelet / skeleton)
    Build,
    /// Build çıktısını ve imzaları doğrulayacak. / Will verify the build output and signatures. (iskelet / skeleton)
    Verify,
    /// Uygulamayı seçilen repository'ye yayımlayacak. / Will publish the app to the chosen repository. (iskelet / skeleton)
    Publish,
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Command::Init => init(),
        Command::Run => not_implemented(
            "run",
            "Uygulamayı yerel makinede veya emülatörde çalıştıracak.",
            "It will run the application on the local machine or in the emulator.",
        ),
        Command::Test => not_implemented(
            "test",
            "Uygulamanın otomatik testlerini çalıştıracak.",
            "It will run the application's automated tests.",
        ),
        Command::Permissions => not_implemented(
            "permissions",
            "ozerk.toml'daki izin beyanlarını denetleyecek ve beyan dışı yetki kullanımını raporlayacak.",
            "It will audit the permission declarations in ozerk.toml and report undeclared capability use.",
        ),
        Command::Build => not_implemented(
            "build",
            "Uygulama paketini, hedef yeniden üretilebilir olacak şekilde derleyecek.",
            "It will build the application package, aiming for reproducible builds.",
        ),
        Command::Verify => not_implemented(
            "verify",
            "Build çıktısını, imzaları ve manifest ile davranış uyumunu doğrulayacak.",
            "It will verify the build output, signatures, and manifest-behavior consistency.",
        ),
        Command::Publish => not_implemented(
            "publish",
            "Uygulamayı geliştiricinin seçtiği repository'ye yayımlayacak.",
            "It will publish the application to the repository chosen by the developer.",
        ),
    }
}

/// TR: Henüz uygulanmamış komutlar için dürüst, iki dilli mesaj basar; çıkış kodu 0.
/// EN: Prints an honest, bilingual message for not-yet-implemented commands; exit code 0.
fn not_implemented(name: &str, tr: &str, en: &str) {
    println!("ozerk {name}: henüz uygulanmadı. {tr}");
    println!("ozerk {name}: not yet implemented. {en}");
}

/// TR: Çalışılan dizinde taslak bir ozerk.toml üretir; var olan dosyanın üzerine yazmaz.
/// EN: Generates a draft ozerk.toml in the working directory; never overwrites an existing file.
fn init() {
    let path = Path::new("ozerk.toml");

    let file = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path);

    match file {
        Ok(mut f) => {
            if let Err(e) = f.write_all(OZERK_TOML_TEMPLATE.as_bytes()) {
                eprintln!("ozerk init: ozerk.toml yazılamadı / could not write ozerk.toml: {e}");
                process::exit(1);
            }
            println!(
                "ozerk init: taslak ozerk.toml oluşturuldu. Alanlar Manifesto §13'ü izler; \
                 uygulamanıza göre düzenleyin."
            );
            println!(
                "ozerk init: draft ozerk.toml created. The fields follow Manifesto §13; \
                 edit them for your application."
            );
        }
        Err(e) if e.kind() == ErrorKind::AlreadyExists => {
            println!("ozerk init: ozerk.toml zaten var; üzerine yazılmadı.");
            println!("ozerk init: ozerk.toml already exists; it was not overwritten.");
        }
        Err(e) => {
            eprintln!("ozerk init: ozerk.toml oluşturulamadı / could not create ozerk.toml: {e}");
            process::exit(1);
        }
    }
}
